<?php
/**
 * CI-ONLY: creates a DISPOSABLE single-site WordPress for real HTTP checks.
 *
 *   php setup-site.php config    <docroot>   writes wp-config.php
 *   php setup-site.php install   <docroot>   runs wp_install()
 *   php setup-site.php provision <docroot>   activates the PACKAGED plugin,
 *                                            sets permalinks, creates test users
 *
 * Refuses non-loopback DB hosts and non-test database names. Test passwords
 * come from EVC_HTTP_PASSWORD (random per CI run, masked, never printed).
 * The staff flag is read from EVC_HTTP_FLAG by wp-config.php at request
 * time, so the same site can be served with the feature on or off.
 */
list(, $mode, $docroot) = array_pad($argv, 3, '');
$host = (string) getenv('EVC_TEST_DB_HOST');
$db = (string) getenv('EVC_WP_TEST_DB_NAME');
$base = getenv('EVC_HTTP_BASE') ?: 'http://127.0.0.1:8089';
$password = (string) getenv('EVC_HTTP_PASSWORD');
if (!in_array($host, array('127.0.0.1', 'localhost', '::1'), true) || !preg_match('/^evc_wp_tests[a-z0-9_]*$/D', $db)) {
    fwrite(STDERR, "Refusing non-loopback host or non-test database.\n");
    exit(2);
}
if (strlen($password) < 16 || !is_dir($docroot)) {
    fwrite(STDERR, "EVC_HTTP_PASSWORD (>=16 chars) and an existing docroot are required.\n");
    exit(2);
}
$parts = parse_url($base);
$_SERVER['HTTP_HOST'] = $parts['host'] . (isset($parts['port']) ? ':' . $parts['port'] : '');
$_SERVER['REQUEST_URI'] = '/';
$_SERVER['SERVER_NAME'] = $parts['host'];

if ($mode === 'config') {
    $salts = '';
    foreach (array('AUTH_KEY', 'SECURE_AUTH_KEY', 'LOGGED_IN_KEY', 'NONCE_KEY', 'AUTH_SALT', 'SECURE_AUTH_SALT', 'LOGGED_IN_SALT', 'NONCE_SALT') as $k) {
        $salts .= "define('$k', " . var_export(bin2hex(random_bytes(32)), true) . ");\n";
    }
    $config = "<?php\n// DISPOSABLE CI SITE — generated by tests/http/setup-site.php\n"
        . 'define(\'DB_NAME\', ' . var_export($db, true) . ");\n"
        . 'define(\'DB_USER\', ' . var_export((string) getenv('EVC_TEST_DB_USER'), true) . ");\n"
        . "define('DB_PASSWORD', getenv('EVC_TEST_DB_PASSWORD') ?: '');\n"
        . 'define(\'DB_HOST\', ' . var_export($host . ':' . (getenv('EVC_TEST_DB_PORT') ?: '3306'), true) . ");\n"
        . "define('DB_CHARSET', 'utf8mb4');\ndefine('DB_COLLATE', '');\n"
        . $salts
        . "\$table_prefix = 'wp_';\n"
        . 'define(\'WP_HOME\', ' . var_export($base, true) . ");\n"
        . 'define(\'WP_SITEURL\', ' . var_export($base, true) . ");\n"
        . "define('WP_DEBUG', false);\ndefine('DISABLE_WP_CRON', true);\ndefine('AUTOMATIC_UPDATER_DISABLED', true);\n"
        . "if (getenv('EVC_HTTP_FLAG') === 'on') { define('EVC_CLUB_STAFF_ENABLED', true); }\n"
        . "if (!defined('ABSPATH')) { define('ABSPATH', __DIR__ . '/'); }\nrequire_once ABSPATH . 'wp-settings.php';\n";
    file_put_contents($docroot . '/wp-config.php', $config);
    echo "wp-config.php written\n";
    exit(0);
}

if ($mode === 'install') {
    define('WP_INSTALLING', true);
    require $docroot . '/wp-load.php';
    require_once ABSPATH . 'wp-admin/includes/upgrade.php';
    $result = wp_install('Evangelou Club HTTP test', 'evc_http_admin', 'admin@example.org', false, '', $password);
    echo is_array($result) ? "WordPress installed\n" : "install failed\n";
    exit(is_array($result) ? 0 : 1);
}

if ($mode === 'provision') {
    require $docroot . '/wp-load.php';
    require_once ABSPATH . 'wp-admin/includes/plugin.php';
    $activated = activate_plugin('evangelou-club/evangelou-club.php');
    if (is_wp_error($activated)) {
        fwrite(STDERR, 'Plugin activation failed: ' . $activated->get_error_message() . "\n");
        exit(1);
    }
    update_option('permalink_structure', '/%postname%/');
    $users = array(
        'evc_http_staff' => array('role' => 'evc_club_staff'),
        'evc_http_editor' => array('role' => 'editor'),
        'evc_http_dual' => array('role' => 'evc_club_staff', 'extra_role' => 'administrator'),
        'evc_http_direct' => array('role' => 'evc_club_staff', 'extra_cap' => 'manage_options'),
    );
    foreach ($users as $login => $spec) {
        $id = wp_insert_user(array('user_login' => $login, 'user_pass' => $password, 'user_email' => $login . '@example.org', 'role' => $spec['role']));
        if (is_wp_error($id)) {
            fwrite(STDERR, "User $login failed\n");
            exit(1);
        }
        $user = new WP_User($id);
        if (isset($spec['extra_role'])) {
            $user->add_role($spec['extra_role']);
        }
        if (isset($spec['extra_cap'])) {
            $user->add_cap($spec['extra_cap']);
        }
    }
    flush_rewrite_rules(false);
    echo "Provisioned: plugin active, permalinks, " . count($users) . " test users\n";
    exit(0);
}

fwrite(STDERR, "Unknown mode\n");
exit(2);
